name: Create Blog Post

on:
  repository_dispatch:
    types: [blog-post-submitted]

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Blog Post Markdown File
        run: |
          POST_DATE=$(date +'%Y-%m-%d')
          FILENAME="content/posts/${{ github.event.client_payload.slug }}.md"

          echo "---" > "$FILENAME"
          echo "title: ${{ github.event.client_payload.title }}" >> "$FILENAME"
          echo "description: ${{ github.event.client_payload.description }}" >> "$FILENAME"
          echo "date: $POST_DATE" >> "$FILENAME"
          echo "draft: false" >> "$FILENAME"
          echo "slug: ${{ github.event.client_payload.slug }}" >> "$FILENAME"
          echo "image: ${{ github.event.client_payload.image }}" >> "$FILENAME"
          echo "tags:" >> "$FILENAME"
          IFS=',' read -ra TAGS <<< "${{ github.event.client_payload.tags }}"
          for tag in "${TAGS[@]}"; do
            echo "  - $tag" >> "$FILENAME"
          done
          echo "---" >> "$FILENAME"
          echo "" >> "$FILENAME"
          echo "${{ github.event.client_payload.content }}" >> "$FILENAME"

      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new blog post: ${{ github.event.client_payload.title }}"
          git push
